### ISSUE TITLE
RISG--Reporting Call/Forms Malfunction

### ISSUE THREAD

**Issue by alandesbonnet** [ecsion/eSeaGrant-Client-Bug-Tracker#878]
In Report Calls, At this URIL:

https://eseagrant.gso.uri.edu/index.php?module=CallReporting&view=Detail&record=100154&mode=linkCustomForms&tab_label=Link%20Custom%20Forms

it shows that "Students Supported" form is linked in the Report Call (see screen shot)

![link_custom_form](https://user-images.githubusercontent.com/18398763/41420649-f8bd70d0-6fc2-11e8-9b2f-230b5e9a1a3e.png)

In Reports, at this URL:

https://eseagrant.gso.uri.edu/index.php?module=Reporting&view=Detail&record=100170

two (2) versions of Students Supported is shown (see screen shot)

![report_tab](https://user-images.githubusercontent.com/18398763/41420738-27eafcba-6fc3-11e8-8216-bfbb2b979cd5.png)

but when I click on either Students Supported in the tab, I get the following message (see screen shot)

![result](https://user-images.githubusercontent.com/18398763/41420788-42fd38a6-6fc3-11e8-8e58-46366333031f.png)

I am setting up a Report Call and cannot get very far with this happening; have not tried any others and will not until this is created. Please correct this. Thank you.
Alan

**Comment by ecsion** [comment]
fixed, please check.

**Comment by alandesbonnet** [comment]
in FORMS, at this URL:

https://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=List&showList=ReportTagged&viewname=214&tab_label=Reporting%20Tagged%20Forms <https://eseagrant.gso.uri.edu/index.php?module=MultipartQuestionStem&view=List&showList=ReportTagged&viewname=214&tab_label=Reporting%20Tagged%20Forms>

I still see 2 forms that appear identical. Why are there 2 forms when I only created one with the 2019 tag? This is what I saw the other day and deleted one as they are identical. This then created the error you fixed from GitHub #878. There should not be 2 forms; it is confusing, and then leads to crashed forms if logic is followed and one is deleted. This needs to be corrected since I don’t know which is the correct one to work on, edit, etc. 

Please advise. Thank you.

Alan Desbonnet
Assistant Director
